import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import './globals.css'

const font = Kanit({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}

export default RootLayout
