import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import './globals.css'

import NavPanel from 'ii/components/NavPanel'
import SidePanel from 'ii/components/SidePanel'

const font = Kanit({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={font.className}>
        <main className="relative min-h-screen p-8">
          <div className="absolute flex top-0 left-0 h-screen w-screen -z-10">
            <div className="flex-1"></div>
            <div className="w-[calc(25vw+1rem)] bg-[#5CCBFF]"></div>
          </div>
          <div className="flex bottom rounded-xl shadow-xl h-[calc(100vh-4rem)] bg-white">
            <div className="flex-1 flex">
              <NavPanel />
              <div className="flex-1 p-4">{children}</div>
            </div>
            <SidePanel />
          </div>
        </main>
      </body>
    </html>
  )
}

export default RootLayout
