import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import './globals.css'

import Image from 'next/image'
import Link from 'next/link'
import NavigationBar from 'ii/components/NavigationBar'

const font = Kanit({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={font.className}>
        <main className="relative min-h-screen p-4">
          <div className="absolute flex top-0 left-0 h-screen w-screen -z-10">
            <div className="flex-1"></div>
            <div className="w-[calc(25vw+0.5rem)] bg-[#5CCBFF]"></div>
          </div>
          <div className="flex bottom rounded-lg shadow-xl h-[calc(100vh-2rem)] bg-white">
            <div className="flex-1 flex">
              <NavigationBar />
              <div className="flex-1 p-4">{children}</div>
            </div>
            <Image
              className="w-1/4 bg-blue-800 rounded-r-lg"
              alt="side-panel-gb"
              width={400}
              height={800}
              src="/side-panel-bg.png"
            />
          </div>
        </main>
      </body>
    </html>
  )
}

export default RootLayout
